apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/seuusuario/seurepositorio-infra.git'
    targetRevision: main
    path: 'frontend'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: frontend-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

